PATH_TO_NOISE = 'saves/'

MAX_HEIGHT = 20
HEIGHT_NOISE_TILE_SIZE = 64
HEIGHT_OCTAVES = [0, 2, 3]
START_HEIGHT_AREA = (-2, -2, 4, 4)
WORLD_CHUNK_SIZE = 16

BIOME_NOISE_TILE_SIZE = 128
BIOME_OCTAVES = [0, 1, 2, 3]

TREES_CHUNK_SIZE = 128
TREES_IN_CHUNK = 350
TREE_AVOIDING_RADIUS = 5

WATER_LEVEL = 5
